import type { Category, Brand, Product } from '../types';

export const CATEGORIES: Category[] = [
    { id: 1, name: 'All', slug: 'all', displayOrder: 1, isActive: true },
    { id: 2, name: 'Men', slug: 'men', displayOrder: 2, isActive: true },
    { id: 3, name: 'Women', slug: 'women', displayOrder: 3, isActive: true },
    { id: 4, name: 'Kids', slug: 'kids', displayOrder: 4, isActive: true },
    { id: 5, name: 'Sports', slug: 'sports', displayOrder: 5, isActive: true },
    { id: 6, name: 'Formal', slug: 'formal', displayOrder: 6, isActive: true },
    { id: 7, name: 'Casual', slug: 'casual', displayOrder: 7, isActive: true },
];

export const BRANDS: Brand[] = [
    { id: 1, name: 'Nike', slug: 'nike', isActive: true },
    { id: 2, name: 'Adidas', slug: 'adidas', isActive: true },
    { id: 3, name: 'Puma', slug: 'puma', isActive: true },
    { id: 4, name: 'Reebok', slug: 'reebok', isActive: true },
    { id: 5, name: 'Vans', slug: 'vans', isActive: true },
    { id: 6, name: 'Converse', slug: 'converse', isActive: true },
];

export const PRODUCTS: Product[] = [
    {
        id: 1,
        sku: 'NIKE-AIR-270',
        name: 'Nike Air Max 270',
        categoryId: 5,
        brandId: 1,
        basePrice: 11499,
        taxRate: 18,
        imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&q=80&w=500',
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        variants: [
            { id: 101, productId: 1, sizeUk: 7, sizeUs: 8, sizeEu: 41, color: 'White/Blue', stockQuantity: 5, reorderLevel: 5, priceAdjustment: 0, isActive: true }
        ]
    },
    {
        id: 2,
        sku: 'ADI-ULTRA-22',
        name: 'Adidas Ultraboost 22',
        categoryId: 5,
        brandId: 2,
        basePrice: 15999,
        taxRate: 18,
        imageUrl: 'https://images.unsplash.com/photo-1587563871167-1ee797455c1b?auto=format&fit=crop&q=80&w=500',
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        variants: [
            { id: 201, productId: 2, sizeUk: 8, sizeUs: 9, sizeEu: 42, color: 'Black/White', stockQuantity: 8, reorderLevel: 5, priceAdjustment: 0, isActive: true },
            { id: 202, productId: 2, sizeUk: 9, sizeUs: 10, sizeEu: 43, color: 'Black/White', stockQuantity: 3, reorderLevel: 5, priceAdjustment: 0, isActive: true }
        ]
    },
    {
        id: 3,
        sku: 'PUMA-RS-X',
        name: 'Puma RS-X³ Puzzle',
        categoryId: 7,
        brandId: 3,
        basePrice: 8499,
        taxRate: 18,
        imageUrl: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&q=80&w=500',
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: 4,
        sku: 'NB-574',
        name: 'New Balance 574 Core',
        categoryId: 7,
        brandId: 4,
        basePrice: 7999,
        taxRate: 18,
        imageUrl: 'https://images.unsplash.com/photo-1539185441755-769473a23570?auto=format&fit=crop&q=80&w=500',
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: 5,
        sku: 'ASICS-KAYANO',
        name: 'Asics Gel-Kayano 29',
        categoryId: 5,
        brandId: 5,
        basePrice: 13999,
        taxRate: 18,
        imageUrl: 'https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2?auto=format&fit=crop&q=80&w=500',
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: 6,
        sku: 'REEBOK-C85',
        name: 'Reebok Club C 85 Vintage',
        categoryId: 7,
        brandId: 4,
        basePrice: 6999,
        taxRate: 18,
        imageUrl: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&q=80&w=500',
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: 7,
        sku: 'VANS-OLD',
        name: 'Vans Old Skool',
        categoryId: 7,
        brandId: 5,
        basePrice: 4499,
        taxRate: 18,
        imageUrl: 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&q=80&w=500',
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: 8,
        sku: 'CON-CHUCK',
        name: 'Converse Chuck Taylor All Star',
        categoryId: 7,
        brandId: 6,
        basePrice: 3999,
        taxRate: 18,
        imageUrl: 'https://images.unsplash.com/photo-1607522370275-f14bc3a5d288?auto=format&fit=crop&q=80&w=500',
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: 9,
        sku: 'HOKA-CLIFTON',
        name: 'Hoka One One Clifton 9',
        categoryId: 5,
        brandId: 1, // Using Nike ID as placeholder for Hoka
        basePrice: 13499,
        taxRate: 18,
        imageUrl: 'https://images.unsplash.com/photo-1588117305388-c2631a279f82?auto=format&fit=crop&q=80&w=500',
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: 10,
        sku: 'SALOMON-SPEED',
        name: 'Salomon Speedcross 5',
        categoryId: 5,
        brandId: 1, // Placeholder
        basePrice: 12499,
        taxRate: 18,
        imageUrl: 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?auto=format&fit=crop&q=80&w=500',
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    }
];
